title: bakje

collections:
  pages:
    output: true
  projects:
    output: true

defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"
  - scope:
      type: "projects"
    values:
      layout: "default"

post_tags:
  C++: "#3d78c4"
  Vulkan: "#c43d4a"
